name: Backup
permissions: {}

on:
  schedule:
    - cron: '0 2 * * *'  # Tous les jours à 2h du matin UTC
  workflow_dispatch:     # Permet de le lancer manuellement aussi

jobs:
  backup:
    name: Backup
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Installer la CLI Clever Cloud
        shell: bash
        run: npm install -g clever-tools

      - name: Déclencher la sauvegarde
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_CLOUD_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_CLOUD_TOKEN }}
          ID_APP: ${{ secrets.CLEVER_CLOUD_ID_APP }}
        run: |
          clever link "$ID_APP"
          clever restart
